### ISSUE TITLE
Limiter starts out allowing too many through?

### ISSUE THREAD

**Issue by adam-p** [RussellLuo/slidingwindow#5]
Using the below code (clone-able from gist [here](https://gist.github.com/89373efeea9dda1c20eedf796948e318.git)), I expect to see output like:
```
[{allowed:1000 disallowed:12445195} {allowed:1001 disallowed:12568861} {allowed:999 disallowed:12469467}]
```

But instead I get this kind of thing:
```
[{allowed:1553 disallowed:12445195} {allowed:1001 disallowed:12568861} {allowed:999 disallowed:12469467}]
```

Note that the first 1-second bucket allowed 1553 rather than 1000. The exact number varies between runs, but it's always significantly more than 1000.

Why is that? (Is it something about the handling of the "previous" window when there is no previous?)

I'm concerned because I plan on aggressively removing limiters when they haven't been used for a few windows (because that would be a rate limit reset anyway), but I don't really want to frequently go over the limit by ~50%.

```go
package main

import (
	"fmt"
	"time"

	sw "github.com/RussellLuo/slidingwindow"
)

func main() {
	const histogramBucketSize = time.Second
	const totalBuckets = 3
	const allowedPerBucket = 1000

	type histoEntry struct {
		allowed    int64
		disallowed int64
	}
	allowedHistogram := make([]histoEntry, totalBuckets)

	lim, _ := sw.NewLimiter(histogramBucketSize, allowedPerBucket, func() (sw.Window, sw.StopFunc) {
		return sw.NewLocalWindow()
	})

	start := time.Now()
	for {
		bucket := time.Now().Sub(start) / histogramBucketSize

		if bucket >= totalBuckets {
			break
		}

		if lim.Allow() {
			allowedHistogram[bucket].allowed++
		} else {
			allowedHistogram[bucket].disallowed++
		}
	}

	fmt.Printf("%+v\n", allowedHistogram)
}
```

**Comment by adam-p** [comment]
Adding even a 1 nanosecond sleep between the creation of the limiter and the start of the loop the effect doesn't happen. So maybe this is something to do with the measured time difference being literally zero at the start?

**Comment by adam-p** [comment]
Below is a simpler version of the test, to help check if my "histogram" math was somehow wrong. The expected output should show 5000 allowed, but instead it's ~5500.

```go
func main() {
	const histogramBucketSize = time.Second
	const allowedPerBucket = 1000

	lim, _ := sw.NewLimiter(histogramBucketSize, allowedPerBucket, func() (sw.Window, sw.StopFunc) {
		return sw.NewLocalWindow()
	})

	start := time.Now()
	var allowed, disallowed int64
	for time.Now().Sub(start) < 5*time.Second {
		if lim.Allow() {
			allowed++
		} else {
			disallowed++
		}
	}

	fmt.Println(allowed, disallowed)
}
```

**Comment by adam-p** [comment]
Another data point: It seems to be related to where the test starts relative to the wall-clock alignment on the window.

This code can be used to target a particular start moment:
```go
	// This is the target fraction of the bucket size where we want to start our test.
	// For example, if it's 0.9, then we want to start 900 milliseconds into a wall-clock-second.
	// If it's 0.0, then we'll start aligned on a wall-clock-second.
	targetClockFraction := float64(0.99)
	for {
		now := time.Now()
		alignmentDiff := now.Sub(now.Truncate(histogramBucketSize))
		if math.Abs(float64(alignmentDiff)/float64(histogramBucketSize)-targetClockFraction) < 0.01 {
			break
		}
	}
```

If `targetClockFraction` is 0.0, then the allowed count for the first window will be 100% of expected (e.g., 1000). If `targetClockFraction` is 0.5, then it will be about 150% (e.g., 1491). If it's 0.99, then it'll be about 199% (e.g., 1981)

**Comment by adam-p** [comment]
I see why it's behaving like this! Obvious in retrospect.

If the window size is 1 second and the test runs for, say, 3 seconds, there will actually be 4 windows in play. The first window is truncated to the second before now, so it will last less than a second. The further we are through the current second, the less long it will last. 

So in the first wall-clock second, we'll allow 1000 requests, then disallow for some milliseconds, then the new window will start and we'll allow again. The first wall-clock second ends and we've allowed through more than 1000 requests in total.

So that's to be expected. It could be "fixed" by aligning the window to the actual start time rather than the wall clock window. But after two windows have elapsed (resetting `lim.prev`) the same behaviour would occur. Unless the window alignment also got reset at that time. Anyway, it would make things more complex. 

I feel like this probably isn't such a big deal, since it can never allow more than double the configured amount. And a sustained heavy request load will stabilize after the first window. 

I'll close this.

**Comment by RussellLuo** [comment]
@adam-p Nice, good job figuring out the reason!

Basically, I think there are two reference systems, between which there is a clock difference (DIFF for short). If DIFF is 500ms, we actually have the following two reference systems:

```
             0 (1000)  1 (1000)  2 (1000)  3 (1000)  4
wall-clock   |---------|---------|---------|---------|---------|
                  ^         ^         ^         ^         ^
actual-clock      |---------|---------|---------|---------|
                  0 (1500)  1 (1000)  2 (1000)  3 (1000)  4
```

Besides the clock difference, another reason for the excess requests during the first window in the view of actual-clock system is that — whenever the limiter starts, it always has the total quota of 1000 requests per second in the first wall-clock second.

One possible solution is to assume a non-zero previous window count for the first wall-clock second. But since no actual requests have been made, we have no idea which value of the previous window count should be assumed. I think it's not a big deal, as you mentioned, since this problem only arises during the first window-size when the limiter starts :)

**Comment by adam-p** [comment]
> I think it's not a big deal, as you mentioned, since this problem only arises during the first window-size when the limiter starts :)

That's not true, though, is it? I think it arises every time the previous window is not-fully-consumed (and in particular if it had no requests at all). 

> One possible solution is to assume a non-zero previous window count for the first wall-clock second. But since no actual requests have been made, we have no idea which value of the previous window count should be assumed. 

That's interesting. It is hard to think of how to do that right, though.

Let's imagine another approach where we mess with curr instead of prev... Let's say that if `lim.curr.count` is zero, then we pre-fill it proportionately to how much of the window has passed. So if we're halfway through the current window, we initialize the count to 500 (of 1000). Then there are only 500 left in the current window. That means that (using your diagram above) for clock durations of...
* 500ms: there are 500 reqs allowed
* 1000ms: there are +500 reqs allowed == 1000 reqs
* 1500ms: +500 = 1500 reqs allowed
* 2000ms: +500 reqs, etc.

With this existing logic that instead looks like:
* 500ms: there are 1000 reqs allowed
* 1000ms: there are +500 reqs allowed == 1500 reqs
* and so on

This isn't bad. It means that the first window doesn't get a full 1000, but it smooths out the big lump allowed.

**Comment by RussellLuo** [comment]
> Let's say that if `lim.curr.count` is zero, then we pre-fill it proportionately to how much of the window has passed.

Hi Adam :) I think it's a good idea, which does make the allowed requests more smooth.

After reading more descriptions about Sliding Window in [Understanding Distributed Systems](https://books.google.co.jp/books?id=mthMEAAAQBAJ&pg=PA201&lpg=PA201&dq=slidingwindow+proportionate+limit&source=bl&ots=pUcs0NizXH&sig=ACfU3U2z7FFxQnHjiUilb_s6-1M-L21zsw&hl=en&sa=X&ved=2ahUKEwig6sbf7cb2AhUTC94KHUUWBzsQ6AF6BAgUEAM#v=onepage&q=slidingwindow%20proportionate%20limit&f=false):

<img width="507" alt="image" src="https://user-images.githubusercontent.com/5109942/158283270-68760f3a-a730-4e8a-9f2b-c8feb100d7e7.png">

I think maybe another solution — with no need to modify the current implementation — is to use a smaller window size, say, 500ms (i.e. 500 requests per 500ms). Then I guess the maximum deviation, if `targetClockFraction` is 0.99, will be reduced to 500? What do you think?

**Comment by adam-p** [comment]
Yes, that's a good approach. There's still a possible 1.99x overshoot, but the absolute value becomes (arbitrarily) small.

I don't think you're suggesting this, but I don't think the library should add this granularity itself -- too potentially confusing for the lib user. But it might be worth mentioning in the README or a comment.

This reminds me of another thing that I am struggling with a bit: What to set the [`Retry-After`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) header to. 

If the prev and curr windows are both maxed out, then the answer is `window_size / allowed_per_window` (rounded up to the nearest second, since that's the header granularity). In other words seconds-per-req. So if there are 30 reqs allowed per 60 seconds and the the previous and current windows are completely consumed, you can be guaranteed than in 2 seconds there will be 1 more req allowed. (As the fraction of the prev window is reduced, that much space is gained in the curr window.)

But if the prev window had zero and the curr window filled up immediately, then the answer is "the rest of the curr window".

There's probably some formula that captures both ends of the spectrum and everything in between, but I don't have it yet. (Although, admittedly, I haven't tried too hard -- my work doesn't depend on it.)

But if the window size is <= 1 second, then the answer always rounds to "1 second".
